<?php

/**
 * @file
 * Islandora Defaults stuff.
 */

/**
 * Implements hook_rdf_namespaces().
 */
function islandora_defaults_rdf_namespaces() {
  return [
      'relators' => 'http://id.loc.gov/vocabulary/relators/',
      'dcterms' => 'http://purl.org/dc/terms/',
      'idloc' => 'http://id.loc.gov/vocabulary/identifiers/',
      'schema' => 'http://schema.org/',
      'bibo' =>	'http://purl.org/ontology/bibo/',
      'bibframe' => 'http://id.loc.gov/ontologies/bibframe/'
  ];
}
/**
 * Implements hook_insert()
 */
function islandora_defaults_node_insert(Drupal\Core\Entity\EntityInterface $entity) {
   // if it is a collection object or a repository item, add in the citable URL
   if ($entity->bundle() == 'collection_object' || $entity->bundle() == 'islandora_object') {
    $url = \Drupal::urlGenerator()->generateFromRoute('<front>', [], ['absolute' => TRUE]);
    $entity->field_citable_url=$url.'node/'.$entity->id();
    \Drupal::logger('islandora_defaults')->info('Setting citable URL on new ' . $entity->bundle() .': ' .  
        $entity->field_citable_url->getString());
    $entity->save();
  }
}

/**
 * Implements hook_apachesolr_index_document_build()
 */
/*
function islandora_defaults_apachesolr_index_document_build(&$document, $entity, $entity_type) {
  if ($entity_type == 'node' && $entity->type == 'islandora_object') {
    $document->addField('ts_field_alternative_title', $entity->field_alternative_title['und'][0]['value']);
    $document->addField('is_field_integer_field_name', $entity->field_integer_field_name['und'][0]['value']);
  }
}*/
